#!/usr/bin/env bash
      
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. $DIR/../_library
. $DIR/_library

assert_argcount 1 ${#}  "Syntax: ${0} <instance_id>"

assert_available jq
assert_available aws

instance_id=$1

ip=$(aws ec2 describe-instances --instance-id $1 | jq ".Reservations[0].Instances[0].PublicIpAddress" -r)
rv=$?

assert_rvzero $rv 

echo $ip